#!/usr/bin/python3
import math
import sys

degree = float(sys.stdin.readline().strip())


radian = math.radians(degree)

sine = math.sin(radian)
cosine = math.cos(radian)
tangent = math.tan(radian)
    
print(f"{degree}度の三角関数:")
print(f"sin({degree}°) = {sine}")
print(f"cos({degree}°) = {cosine}")
print(f"tan({degree}°) = {tangent}")
